version: '3'
services:
  dev-api:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    working_dir: /src/api-demo
    ports:
      - 5072:5072
    volumes:
      - ./api-demo.sln:/src/api-demo.sln
      - ./api-demo:/src/api-demo
    # binding host "0.0.0.0", or you can't access on real machine
    command: dotnet run --urls "http://0.0.0.0:5072"
  dev-admin:
    build:
      dockerfile: Dockerfile.admin-ui
      context: .
      target: base
    environment:
      - API_URL=http://dev-api:5072
    ports:
      - 5073:5073
    volumes:
      - ./admin-ui:/src/admin-ui
    command: yarn admin dev